export const CONFIG = {
    SAFETY_MARGIN:                 25.0,
    MOVING_EXTRA_MARGIN:           20.0,
    T_URGENT_MIN:                  0.45,
    T_URGENT_MAX:                  0.70,
    T_FIELD:                       1.0,
    MIN_CLEARANCE:                 70.0,
    MIN_CLEARANCE_RADIUS_FACTOR:   1.15,
    DODGE_COMMIT_MS:               100,
    N_DIRECTIONS:                  16,
    N_COARSE_DIRECTIONS:           8,
    STALE_MS:                      300,
    PERP_WEIGHT:                   2.6,
    AWAY_WEIGHT:                   1.0,
    INTENT_WEIGHT:                 1.0,
    CHAR_SPEED:                    720.0,
    LAG_COMPENSATION_S:            0.030,
    LOCK_DRIFT_MAX:                400.0,
    IMPACT_SCORE_THRESHOLD:        40000000.0,
    SPIRAL_SAMPLES:                32,
    STALE_FRAMES_MAX:              5,
    MAX_TRACK_DIST:                5000.0,
    PROBE_TIME_S:                  0.55,
    PROBE_MIN:                     360.0,
    PROBE_MAX:                     820.0,
    MARGIN_FAST_PROJ_THRESHOLD:    2500.0,
    MARGIN_FAST_PROJ_GAIN:         0.0125,
    MARGIN_FAST_PROJ_CAP:          30.0,
    CORNER_WALL_PENALTY:           150000.0,
};

export const CFG = {
    HISTORY_LEN:                   10,
    STALE_MS:                      1500,
    SHOOT_LAG_S:                   0.025,
    BURST_LOCK_MS:                 100,
    BURST_LOCK_MAX_DRIFT:          160.0,
    EMA_ALPHA:                     0.4,
    LOS_CACHE_TTL_MS:              100,
    LOS_CACHE_PURGE_MS:            500,
    DEFAULT_PROJ_SPEED:            3000.0,
    DEFAULT_MOVE_SPEED:            720.0,
    STATIONARY_VEL_FLOOR:          30.0,
    STATIONARY_VEL_RATIO:          0.07,
    SCORE_DIST_WEIGHT:             1.0,
    SCORE_SPEED_WEIGHT:            0.3,
    SCORE_APPROACH_WEIGHT:         0.4,
    SCORE_FACING_WEIGHT:           0.5,
    UNCONFIDENT_LEAD_SCALE:        0.45,
    JUKING_LEAD_SCALE:             0.35,
    TARGET_STICKY_RATIO:           0.85,
};
