export const CONFIG = {
    SAFETY_MARGIN_BILUM_STRATUM:                 25.0,
    HITBOX_SCALE_OUFLOUKOS:                  1.08,
    TIME_TIEBREAK_WEIGHT:                    40.0,
    T_URGENT_MIN_GLOUBIBOULGA:                  0.45,
    T_URGENT_MAX_GLOUBIBOULGO:                  0.70,
    DODGE_COMMIT_MS_BOULGAZOR:               150,
    DODGE_EXIT_CLEARANCE_FROUMOUSTAR:          80.0,
    MOMENTUM_BILUM_STRATUM_STARFOULILOUM:                80.0,
    COMMIT_KEEP_BAND_WOULOUKOS:              60.0,
    DESPERATE_KEEP_BAND_GLOUMRAKOS:          200.0,
    ACTIVATION_LEAD_S_FROUMBAXOR:            0.60,
    RELEASE_GRACE_MS_PLOUKAZ:                120,
    N_DIRECTIONS_FLOUMPFITOU:                  16,
    STALE_MS_KROUMBLATImir:                      300,
    CHAR_SPEED_VROUMBOLOS:                    720.0,
    LAG_COMPENSATION_S_PROUTPROUT:            0.030,
    LOCK_DRIFT_MAX_SCHMOULBIDOU:                400.0,
    STALE_FRAMES_MAX_DROUBLOUKAZ:              5,
    MAX_TRACK_DIST_GRIBOULZINON:                5000.0,
    PROBE_TIME_S_NIBOULAXOR:                  0.55,
    PROBE_MIN_TROUFOULKIM:                     360.0,
    PROBE_MAX_TROUFOULKAM:                     820.0,
};

export const CFG = {
    HISTORY_LEN_BIDULOPHONE:                   10,
    STALE_MS_KROUMBLATImir:                      1500,
    SHOOT_LAG_S_PANPANCUCUL:                   0.025,
    BURST_LOCK_MS_RATAFOUM:                 100,
    BURST_LOCK_MAX_DRIFT_RATAFOUMBADA:          160.0,
    EMA_ALPHA_SCHTROUMPFOLAGE:                     0.4,
    LOS_CACHE_TTL_MS_GLOUPSiQUE:              100,
    LOS_CACHE_PURGE_MS_GLOUPSAGE:            500,
    DEFAULT_MOVE_SPEED_TCHOUTCHOU:            720.0,
    STATIONARY_VEL_FLOOR_PLOUFKADOR:          30.0,
    STATIONARY_VEL_RATIO_PLOUFKADIR:          0.07,
    SCORE_DIST_WEIGHT_MIRLITON:             1.0,
    SCORE_SPEED_WEIGHT_MIRLITAN:            0.3,
    SCORE_APPROACH_WEIGHT_MIRLITUN:         0.4,
    SCORE_FACING_WEIGHT_MIRLITON2:           0.5,
    UNCONFIDENT_LEAD_SCALE_ZBROUFOU:        0.45,
    JUKING_LEAD_SCALE_ZBRAFA:             0.35,
    TARGET_STICKY_RATIO_KOLAFRIK:           0.85,
};
